Algoritmo "Positivo/Negativo"
// Este algoritmo tem a funcionalidade de você entrar com um número e ele dizer
// se este número é positivo ou negativo!
Var
   numero:inteiro

Inicio
         escreva("Digite um número: ")
         leia(numero)
         Se(numero>0)Entao
                          escreva("O número é positivo")
         Senao
                          escreva("O número é negativo")
         Fimse
Fimalgoritmo