Algoritmo "Masculino ou Feminino"
// Este algoritmo tem a funcionalidade de que se você entrar com a letra "M",
// o algoritmo interpreta como masculino e se você entrar com qualquer outra
// letra, ele interpreta como feminino"
Var
   Letra:caractere

Inicio
     escreval("Digite uma letra:")
     leia(Letra)

     Se Letra = "m" entao
         escreva("Masculino")
     Senao
         escreva("Feminino")
     Fimse
Fimalgoritmo